name: 'default'
author: 'Xu wayen'
output_path : 'DATE_TIME'
seed: 1958
play_steps: 10

# navigation config
habitat_config_path: 'configs/habitat_default.yaml'

max_moves: 20
success_distance: 1.0
use_office_reward: True
discount_rate: 0.98

# backbone
preprocess_model: 'resnet34'

# normal model-based learning 
normal_mbase:
  envnet_layer_num: [516,200,100,200,512]
  policynet_layer_num: [512,200,100,200,3]
  valuenet_layer_num: [512,250,100,50,1]

  envnet_train_epochs: 10
  policynet_train_epochs: 10

  envnet_train_sample_num: 10
  envnet_train_batchsize: 30
  policynet_train_sample_num: 10
  policy_train_batchsize: 30

  env_train_batchsize: 10
  
  envnet_train_lr: 0.1
  envnet_train_momentun: 0.9
  env_train_epoches: 20

  policy_train_lr: 0.1

  envpolicy_train_epoches: 20
  policy_train_epoches: 20
