name: 'default'
author: 'Xu wayen'
output_path : 'DATE_TIME'
seed: 2023
play_steps: 20

# navigation config
habitat_config_path: 'configs/habitat_default.yaml'

max_moves: 500
success_distance: 1.0
use_office_reward: True
discount_rate: 0.98

# backbone
preprocess_model: 'resnet34'

# normal model-based learning 
normal_mbase:
  envnet_layer_num: [516,512,512,512]
  policynet_layer_num: [512,150,30,3]
  valuenet_layer_num: [512,150,30,1]

  envnet_train_epochs: 200
  policynet_train_epochs: 200

  envnet_train_sample_num: 40
  envnet_train_batchsize: 40
  policynet_train_sample_num: 40
  policy_train_batchsize: 40

  env_train_batchsize: 120
  
  envnet_train_lr: 0.1
  envnet_train_momentun: 0.9
  env_train_epoches: 20

  policy_train_lr: 0.1

  envpolicy_train_epoches: 100
  policy_train_epoches: 20
