# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - _self_
  - habitat/task/measurements:
    - distance_to_goal
    - success
    - spl
    - distance_to_goal_reward
    - num_steps
    - top_down_map
    

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256
  dataset:
    data_path: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz