name: 'default'
author: 'Xu wayen'
output_path : 'DATE_TIME'
seed: 2023
play_steps: 20

# navigation config
habitat_config_path: 'configs/habitat_default.yaml'

max_moves: 500
success_distance: 1.0
use_office_reward: True
discount_rate: 0.98

# backbone
preprocess_model: 'resnet34'

# Mapping
vision_range: 100
map_resolution: 0.05 # UNIT: cm
